import JSZip from "jszip";
import type {
  DetectionSettings,
  ExportSettings,
  ExtractedAsset,
  RGB,
  SourceImage,
} from "@/state/storyboard-types";
import { buildManifest } from "./manifest";
import { slugifyName } from "./naming";
import { rgbaToHex } from "./image-utils";

const EXPORT_ROOT = "storyboard-export";
const EXPORT_ROOT_BY_PRESET: Record<ExportSettings["platformPreset"], string> = {
  generic: EXPORT_ROOT,
  web: "storyboard-web",
  ios: "storyboard-ios",
  android: "storyboard-android",
};

type ExportedFile = { assetId: string; pngPath?: string; pixelSvgPath?: string };

export function selectAssetsForExport(assets: ExtractedAsset[], scope: ExportSettings["scope"]) {
  const active = assets.filter((asset) => !asset.rejected);
  if (scope === "selected") {
    const selected = active.filter((asset) => asset.selected);
    return selected.length ? selected : active;
  }
  return active;
}

export function assetFileBase(asset: ExtractedAsset, settings: ExportSettings) {
  const prefix = slugifyName(settings.filePrefix || "asset", settings.namingStyle);
  const slug = slugifyName(asset.slug || asset.name, settings.namingStyle);
  return slug.startsWith(prefix) ? slug : `${prefix}-${slug}`;
}

export function platformAssetFileBase(asset: ExtractedAsset, settings: ExportSettings) {
  const base = assetFileBase(asset, settings);
  return settings.platformPreset === "android" ? slugifyName(base, "snake") : base;
}

function exportRoot(settings: ExportSettings) {
  return EXPORT_ROOT_BY_PRESET[settings.platformPreset];
}

function manifestPath(settings: ExportSettings) {
  return `${exportRoot(settings)}/manifest/asset-manifest.json`;
}

function readmePath(settings: ExportSettings) {
  return `${exportRoot(settings)}/README.txt`;
}

function pngPathFor(base: string, settings: ExportSettings) {
  const root = exportRoot(settings);
  switch (settings.platformPreset) {
    case "web":
      return `${root}/src/assets/png/${base}.png`;
    case "ios":
      return `${root}/Assets.xcassets/${base}.imageset/${base}.png`;
    case "android":
      return `${root}/app/src/main/res/drawable-nodpi/${base}.png`;
    default:
      return `${root}/assets/png/${base}.png`;
  }
}

function pixelSvgPathFor(base: string, settings: ExportSettings) {
  const root = exportRoot(settings);
  switch (settings.platformPreset) {
    case "web":
      return `${root}/src/assets/svg-pixel/${base}.svg`;
    case "ios":
    case "android":
      return `${root}/reference/svg-pixel/${base}.svg`;
    default:
      return `${root}/assets/svg-pixel/${base}.svg`;
  }
}

function iosContentsPathFor(base: string, settings: ExportSettings) {
  return `${exportRoot(settings)}/Assets.xcassets/${base}.imageset/Contents.json`;
}

function webAssetMapPath(settings: ExportSettings) {
  return `${exportRoot(settings)}/src/asset-map.ts`;
}

export function getZipPreviewPaths(assets: ExtractedAsset[], settings: ExportSettings) {
  const paths: string[] = [];
  for (const asset of assets) {
    const base = platformAssetFileBase(asset, settings);
    if (settings.includePng) {
      paths.push(pngPathFor(base, settings));
      if (settings.platformPreset === "ios") paths.push(iosContentsPathFor(base, settings));
    }
    if (settings.includePixelSvg) paths.push(pixelSvgPathFor(base, settings));
  }
  if (settings.platformPreset === "web" && assets.length) paths.push(webAssetMapPath(settings));
  if (settings.includeManifest) paths.push(manifestPath(settings));
  if (settings.includeReadme) paths.push(readmePath(settings));
  return paths;
}

async function dataUrlToBlob(dataUrl: string): Promise<Blob> {
  const response = await fetch(dataUrl);
  return await response.blob();
}

function escapeXml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function createPixelSvg(asset: ExtractedAsset) {
  const { w, h } = asset.bbox;
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" role="img" aria-labelledby="title desc">
  <title id="title">${escapeXml(asset.name)}</title>
  <desc id="desc">Pixel SVG generated by Storyboard. This preserves the crop as embedded raster image data; it is not editable vector geometry.</desc>
  <image href="${asset.preview}" width="${w}" height="${h}" preserveAspectRatio="xMidYMid meet" />
</svg>`;
}

function buildReadme(params: {
  sourceImage: SourceImage;
  assets: ExtractedAsset[];
  detectionSettings: DetectionSettings;
  exportSettings: ExportSettings;
  backgroundColor: RGB | null;
}) {
  const bg = rgbaToHex(params.backgroundColor) ?? "unknown";
  return [
    "Storyboard Export",
    "",
    `Source: ${params.sourceImage.name}`,
    `Source size: ${params.sourceImage.width}x${params.sourceImage.height}`,
    `Assets exported: ${params.assets.length}`,
    `Platform preset: ${params.exportSettings.platformPreset}`,
    `Background estimate: ${bg}`,
    "",
    "Formats",
    "- PNG: transparent raster crop.",
    "- Pixel SVG: SVG wrapper that embeds the PNG crop. It preserves appearance but is not editable vector geometry.",
    "- Manifest: JSON metadata for wiring assets into code.",
    "",
    "Detection Settings",
    `- Threshold: ${params.detectionSettings.threshold}`,
    `- Sensitivity: ${params.detectionSettings.sensitivity}`,
    `- Minimum component area: ${params.detectionSettings.minComponentArea}`,
    `- Merge distance: ${params.detectionSettings.mergeDistance}`,
    `- Padding: ${params.detectionSettings.padding}`,
    `- Preserve shadows: ${params.detectionSettings.preserveShadows ? "yes" : "no"}`,
    "",
    "Generated locally in the browser by Storyboard.",
  ].join("\n");
}

function buildIosContents(filename: string) {
  return JSON.stringify(
    {
      images: [
        {
          filename,
          idiom: "universal",
          scale: "1x",
        },
      ],
      info: {
        author: "storyboard",
        version: 1,
      },
    },
    null,
    2,
  );
}

function webRelativeUrl(path: string, settings: ExportSettings) {
  const srcPrefix = `${exportRoot(settings)}/src/`;
  return path.startsWith(srcPrefix) ? `./${path.slice(srcPrefix.length)}` : path;
}

function buildWebAssetMap(params: {
  assets: ExtractedAsset[];
  exportSettings: ExportSettings;
  exportedFiles: ExportedFile[];
}) {
  const fileMap = new Map(params.exportedFiles.map((file) => [file.assetId, file]));
  const entries = params.assets.map((asset) => {
    const files = fileMap.get(asset.id);
    const png = files?.pngPath
      ? `new URL(${JSON.stringify(webRelativeUrl(files.pngPath, params.exportSettings))}, import.meta.url).href`
      : "undefined";
    const pixelSvg = files?.pixelSvgPath
      ? `new URL(${JSON.stringify(webRelativeUrl(files.pixelSvgPath, params.exportSettings))}, import.meta.url).href`
      : "undefined";

    return `  ${JSON.stringify(asset.slug)}: {
    name: ${JSON.stringify(asset.name)},
    png: ${png},
    pixelSvg: ${pixelSvg},
  }`;
  });

  return `export const storyboardAssets = {
${entries.join(",\n")}
} as const;

export type StoryboardAssetKey = keyof typeof storyboardAssets;
`;
}

export async function exportAssetZip(params: {
  sourceImage: SourceImage;
  assets: ExtractedAsset[];
  detectionSettings: DetectionSettings;
  exportSettings: ExportSettings;
  backgroundColor: RGB | null;
}): Promise<Blob> {
  const zip = new JSZip();
  const exportedFiles: ExportedFile[] = [];

  for (const asset of params.assets) {
    const base = platformAssetFileBase(asset, params.exportSettings);
    const files: ExportedFile = {
      assetId: asset.id,
    };

    if (params.exportSettings.includePng) {
      const path = pngPathFor(base, params.exportSettings);
      zip.file(path, await dataUrlToBlob(asset.preview));
      files.pngPath = path;

      if (params.exportSettings.platformPreset === "ios") {
        zip.file(iosContentsPathFor(base, params.exportSettings), buildIosContents(`${base}.png`));
      }
    }

    if (params.exportSettings.includePixelSvg) {
      const path = pixelSvgPathFor(base, params.exportSettings);
      zip.file(path, createPixelSvg(asset));
      files.pixelSvgPath = path;
    }

    exportedFiles.push(files);
  }

  if (params.exportSettings.platformPreset === "web") {
    zip.file(
      webAssetMapPath(params.exportSettings),
      buildWebAssetMap({ ...params, exportedFiles }),
    );
  }

  if (params.exportSettings.includeManifest) {
    const manifest = buildManifest({
      sourceImage: params.sourceImage,
      assets: params.assets,
      detectionSettings: params.detectionSettings,
      exportSettings: params.exportSettings,
      backgroundColor: params.backgroundColor,
      exportedFiles,
    });
    zip.file(manifestPath(params.exportSettings), JSON.stringify(manifest, null, 2));
  }

  if (params.exportSettings.includeReadme) {
    zip.file(readmePath(params.exportSettings), buildReadme(params));
  }

  return await zip.generateAsync({ type: "blob" });
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
